{% set version = "1.1-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-survauc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/survAUC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survAUC/survAUC_{{ version }}.tar.gz
  sha256: 05351dc24fe97c24eb9c3d2e4ec9a327733c6673bdc3ad551e588ed4cfb47924

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rms
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rms
    - r-survival

test:
  commands:
    - $R -e "library('survAUC')"           # [not win]
    - "\"%R%\" -e \"library('survAUC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=survAUC
  license: GPL-2.0-only
  summary: The package provides a variety of functions to estimate time-dependent true/false positive rates and AUC curves from a set of censored survival data.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
