{% set version = '1.0-5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-survauc
  version: {{ version|replace("-", "_") }}

source:
  fn: survAUC_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/survAUC_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/survAUC/survAUC_{{ version }}.tar.gz
  sha256: f9ff65742d827f37cdac799e81939726d50047dfeb2740b1d4008615054a922d

build:
  merge_build_host: True  # [win]
  number: 1003
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-survival

  run:
    - r-base
    - r-survival

test:
  commands:
    - $R -e "library('survAUC')"  # [not win]
    - "\"%R%\" -e \"library('survAUC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=survAUC
  license: GPL-2
  summary: The package provides a variety of functions to estimate time-dependent true/false
    positive rates and AUC curves from a set of censored survival data.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
