appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qnzcZfSUWx3BmVXTbKVEpcFddg6xRw9mX5ajBk8PMwFMTQ+jSbxdKqTWdsQUrGZR2/g9UXzicuXmd7MoUjWDwlkimzcht6AZLamFYtv7BtdSDr9oSQ47l57BhfntEI9684zap9okzMI6M39lnhQoPhBdz3M9l+grUhVn5o0cLmNOnjJFdm/044OmVUhyVlGgOhjW6MKfBYqrnmciZdIZmcJD0ZX0HmuphVNYx7PGA2IPiDo6Jb9vsYR3Ga5/eFRat9K/VMPasiUCTjBaoVGbNtO+Z+VkUa4iAJDPrsL9gq3+phHvxSg0o2UanyGDRmqKuoE47BTFYeZFRsEFmEeXYQ2BbJqrkrfIki+HXVxMAQ6JqWxpqOjqk68qyodoH/jtVQyJVH8KgYWTXSsKeYFGjMsydfnkwV2myy5vkwe7ItjbZ3rgiCzLdHD/0M71jp2ml1ctJlIJVald2S6sDN5iUrSLMPsMde3HF6TVMmVIYdEB3aHH5d86a0qKhfA3Az1Bq/8uIDVpuRmEMSWLnJK3VNRd/LFAl/9uwBGxYCLDoJYL4G85M/qijpOngBRE3CRkHX6Nz5ySKm9/nktSDaKT+cQIoPTqKXPRLBX6S2MPtvoBd5s/3oMMDXAkFR141nHrHR+db830lf0t+oi/wOSKYzKFtq3Ae3b++TOwPu9GHXE=}
bot:
  automerge: true
