travis:
  secure:
    BINSTAR_TOKEN: 1aRgESdxVVewaVg0NmBH5XYG2aWtjRQoXUhxCXkKcUFFf9y1y9o7xOBBOGvhh619Qu/OsImAYgCaKTxexcLRxQcjN5YScSnNK2AE0tGpo6KtyGjDZoFaFS2NV1AoNeWkhQVe9i020xqQbDxpKoI/EejPbyzuLaTWZ/yeQhGIv7bQYL/TqwQBp9D1H7DzjSaWwNNn4+/Jwd2y5nNU40ZvQ/yrl5rRC5m3qbc8CAFO45NR62dAWz0IbDKsdNtqO8ZZ73PbVayHERnD+cg/E1iS7Iwcb9sYBfiAmJpEmMkp2cgZ4nutC7XVIWC6OYiGtiJeStwvJ7jIFsVu693wiaN0xVPyFcgtqUjnTHgIMUCvqL/dSgXJLc+l0P1eGo56+jyy9lK/+q9IhrDzkMrZUI87UYt1yvPwK9gwik6y+lZZR8XZu7hXK5tw5OS27tCsU3o6raDXaC1ZVz2k69LiCHWnB9yfbJ8TmRkHnfAN1QiGxfAtTSL/eD04sNeUhaHWHkOj7Il0j4QtC0/+6U0Y7AjmRp5Z72ZDhOY1aJrcO21jYw1oNUiJzcTQ0JZoOxh9RwqrL5noETv6hxjLbXVcskcVRL4ElalwZV4ao0dez+MnReq6l1q2ptzi6uAQZm3vIURyEeJto7lJ7HGPxDsyzdpIPkhgHfW54BfazDl9OvdQHnQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
